// <auto-generated />
using System;
using FEEE.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FEEE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124192445_FixSubjectSectionRelation")]
    partial class FixSubjectSectionRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21A967D838E2A");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.OperationType", b =>
                {
                    b.Property<int>("OperationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OperationTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OperationTypeId")
                        .HasName("PK__Operatio__FF7FE533B7801D67");

                    b.ToTable("OperationTypes");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SectionId")
                        .HasName("PK__Sections__80EF089226AFA231");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("SemesterId");

                    b.HasIndex("YearId");

                    b.ToTable("Semesters", (string)null);
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("FatherName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MinisterialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UniversityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("YearId")
                        .HasColumnType("int")
                        .HasColumnName("YearID");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A790CFDD26F");

                    b.HasIndex("CityId");

                    b.HasIndex("SectionId");

                    b.HasIndex("YearId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentArchive", b =>
                {
                    b.Property<int>("StudentArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentArchiveID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentArchiveId"));

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ArchiveNumber")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("StudentArchiveId")
                        .HasName("PK__StudentA__BE0F4C296DF0556B");

                    b.HasIndex("OperationType");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("StudentArchive", (string)null);
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentPromotion", b =>
                {
                    b.Property<int>("StudentPromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentPromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentPromotionId"));

                    b.Property<byte?>("Decision")
                        .HasColumnType("tinyint");

                    b.Property<int>("FromYearId")
                        .HasColumnType("int")
                        .HasColumnName("FromYearID");

                    b.Property<DateTime?>("PromotionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("ToYearId")
                        .HasColumnType("int")
                        .HasColumnName("ToYearID");

                    b.HasKey("StudentPromotionId")
                        .HasName("PK__StudentP__A1CA55D8E2A43EDC");

                    b.HasIndex("FromYearId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ToYearId");

                    b.ToTable("StudentPromotion", (string)null);
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentSubject", b =>
                {
                    b.Property<int>("StudentSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentSubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentSubjectId"));

                    b.Property<byte>("Semester")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int>("YearId")
                        .HasColumnType("int")
                        .HasColumnName("YearID");

                    b.HasKey("StudentSubjectId")
                        .HasName("PK__StudentS__54F6B8C1332DC99B");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("YearId");

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("HasPractical")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("YearId")
                        .HasColumnType("int")
                        .HasColumnName("YearID");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA38869824235");

                    b.HasIndex("SectionId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("YearId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCACF5B11963");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Year", b =>
                {
                    b.Property<int>("YearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YearID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("YearId")
                        .HasName("PK__Years__C33A18ADD0DBE850");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Semester", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "Year")
                        .WithMany("Semesters")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Student", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.City", "City")
                        .WithMany("Students")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Students_Cities");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Students_Sections");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "Year")
                        .WithMany("Students")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Students_Years");

                    b.Navigation("City");

                    b.Navigation("Section");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentArchive", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.OperationType", "OperationTypeNavigation")
                        .WithMany("StudentArchives")
                        .HasForeignKey("OperationType")
                        .IsRequired()
                        .HasConstraintName("FK_StudentArchive_OperationTypes");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Student", "Student")
                        .WithMany("StudentArchives")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentArchive_Students");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.User", "User")
                        .WithMany("StudentArchives")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentArchive_Users");

                    b.Navigation("OperationTypeNavigation");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentPromotion", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "FromYear")
                        .WithMany("StudentPromotionFromYears")
                        .HasForeignKey("FromYearId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentPromotion_FromYear");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Student", "Student")
                        .WithMany("StudentPromotions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentPromotion_Students");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "ToYear")
                        .WithMany("StudentPromotionToYears")
                        .HasForeignKey("ToYearId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentPromotion_ToYear");

                    b.Navigation("FromYear");

                    b.Navigation("Student");

                    b.Navigation("ToYear");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.StudentSubject", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Students");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Subjects");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "Year")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("YearId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentSubjects_Years");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Subject", b =>
                {
                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Section", "Section")
                        .WithMany("Subjects")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Sections");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Semester", "Semester")
                        .WithMany("Subjects")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subjects_Semesters");

                    b.HasOne("FEEE.Infrastructure.Persistence.Models.Year", "Year")
                        .WithMany("Subjects")
                        .HasForeignKey("YearId")
                        .HasConstraintName("FK_Subjects_Years");

                    b.Navigation("Section");

                    b.Navigation("Semester");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.City", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.OperationType", b =>
                {
                    b.Navigation("StudentArchives");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Section", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Semester", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Student", b =>
                {
                    b.Navigation("StudentArchives");

                    b.Navigation("StudentPromotions");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Subject", b =>
                {
                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.User", b =>
                {
                    b.Navigation("StudentArchives");
                });

            modelBuilder.Entity("FEEE.Infrastructure.Persistence.Models.Year", b =>
                {
                    b.Navigation("Semesters");

                    b.Navigation("StudentPromotionFromYears");

                    b.Navigation("StudentPromotionToYears");

                    b.Navigation("StudentSubjects");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
